<a href="https://colab.research.google.com/github/rajeshtikaddar/Internship/blob/main/Feature_Engineering_%26_ML_Dataset_Preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dataset

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = {
    "Failed_Logins": [2, 18, 1, 22, 3, 15],
    "Login_Time": ["10:00 AM", "2:00 AM", "11:00 AM", "3:15 AM", "9:30 AM", "2:45 AM"],
    "Country": ["India", "Russia", "India", "Unknown", "India", "China"],
    "Device_Type": ["Laptop", "Desktop", "Mobile", "Laptop", "Desktop", "Mobile"],
    "Suspicious_Activity": ["No", "Yes", "No", "Yes", "No", "Yes"]
}

df = pd.DataFrame(data)
print(df)

   Failed_Logins Login_Time  Country Device_Type Suspicious_Activity
0              2   10:00 AM    India      Laptop                  No
1             18    2:00 AM   Russia     Desktop                 Yes
2              1   11:00 AM    India      Mobile                  No
3             22    3:15 AM  Unknown      Laptop                 Yes
4              3    9:30 AM    India     Desktop                  No
5             15    2:45 AM    China      Mobile                 Yes

**DataSet Exploration**

In [ ]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Failed_Logins        6 non-null      int64
 1   Login_Time           6 non-null      object
 2   Country              6 non-null      object
 3   Device_Type          6 non-null      object
 4   Suspicious_Activity  6 non-null      object
dtypes: int64(1), object(4)
memory usage: 372.0+ bytes

       Failed_Logins
count       6.000000
mean       10.166667
std         9.239408
min         1.000000
25%         2.250000
50%         9.000000
75%        17.250000
max        22.000000

**Feature Engineering **

In [ ]:
high_risk = ["Russia","China","Unknown"]
df["High_Risk_Country"] = df["Country"].apply(
  lambda x: 1 if x in high_risk else 0
)

In [ ]:
df.head()

,Failed_Logins,Login_Time,Country,Device_Type,Suspicious_Activity,High_Risk_Country
0,2,10:00 AM,India,Laptop,No,0
1,18,2:00 AM,Russia,Desktop,Yes,1
2,1,11:00 AM,India,Mobile,No,0
3,22,3:15 AM,Unknown,Laptop,Yes,1
4,3,9:30 AM,India,Desktop,No,0

Login Time

In [ ]:
df["Hour"] = pd.to_datetime(
    df["Login_Time"],
    errors="coerce"
).dt.hour

df["Night_Login"] = (df["Hour"] < 6 ).astype(int)

df[["Login_Time","Hour"]].head(10)

/tmp/ipykernel_867/2988889548.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Hour"] = pd.to_datetime(

  Login_Time  Hour
0   10:00 AM    10
1    2:00 AM     2
2   11:00 AM    11
3    3:15 AM     3
4    9:30 AM     9
5    2:45 AM     2

In [ ]:
df.head()

,Failed_Logins,Login_Time,Country,Device_Type,Suspicious_Activity,High_Risk_Country,Hour,Night_Login
0,2,10:00 AM,India,Laptop,No,0,10,0
1,18,2:00 AM,Russia,Desktop,Yes,1,2,1
2,1,11:00 AM,India,Mobile,No,0,11,0
3,22,3:15 AM,Unknown,Laptop,Yes,1,3,1
4,3,9:30 AM,India,Desktop,No,0,9,0

**Create Login Risk Score **

In [ ]:
df["Login_Risk_Score"] = (
    df["Failed_Logins"]*0.6 +
    df["High_Risk_Country"]*20 +
    df["Night_Login"]*10
)

In [ ]:
df.head()

,Failed_Logins,Login_Time,Country,Device_Type,Suspicious_Activity,High_Risk_Country,Hour,Night_Login,Login_Risk_Score
0,2,10:00 AM,India,Laptop,No,0,10,0,1.2
1,18,2:00 AM,Russia,Desktop,Yes,1,2,1,40.8
2,1,11:00 AM,India,Mobile,No,0,11,0,0.6
3,22,3:15 AM,Unknown,Laptop,Yes,1,3,1,43.2
4,3,9:30 AM,India,Desktop,No,0,9,0,1.8

**Encoding Categorial Features **

In [ ]:
from sklearn.preprocessing import LabelEncoder

le =  LabelEncoder()

df["Device_Type"] = le.fit_transform(
    df["Device_Type"]
)

df["Suspicious_Activity"] = le.fit_transform(
    df["Suspicious_Activity"]
)

df.head()

,Failed_Logins,Login_Time,Country,Device_Type,Suspicious_Activity,High_Risk_Country,Hour,Night_Login,Login_Risk_Score
0,2,10:00 AM,India,1,0,0,10,0,1.2
1,18,2:00 AM,Russia,0,1,1,2,1,40.8
2,1,11:00 AM,India,2,0,0,11,0,0.6
3,22,3:15 AM,Unknown,1,1,1,3,1,43.2
4,3,9:30 AM,India,0,0,0,9,0,1.8

**Feature Selections And Final Dataset **

In [ ]:
final_dataset = df[
    [
    "Failed_Logins",
    "Device_Type",
    "High_Risk_Country",
    "Night_Login",
    "Login_Risk_Score",
    "Suspicious_Activity"
    ]
]

final_dataset.head()

,Failed_Logins,Device_Type,High_Risk_Country,Night_Login,Login_Risk_Score,Suspicious_Activity
0,2,1,0,0,1.2,0
1,18,0,1,1,40.8,1
2,1,2,0,0,0.6,0
3,22,1,1,1,43.2,1
4,3,0,0,0,1.8,0

Target Variable: Suspicious_Activity

Input Features: Failed_Logins, Country, Device_Type, High_Risk_Country, Night_Login, Login_Risk_Score, Hour

Most Important Features Failed_Logins, High_Risk_Country, Night_Login, Login_Risk_Score